apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-ns
data:
  MONGODB_URI: "mongodb://mongodb-svc:27017/<DB_NAME>"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://<ELB_DNS>/api"
  NEXTAUTH_URL: "http://<ELB_DNS>"