FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json tsconfig.json ./

COPY script ./script
COPY .db ./.db

RUN npm install && npm install --save-dev @types/mongoose

ENV NODE_ENV=development

CMD ["npx", "ts-node", "--project", "script/tsconfig.json", "script/migrate-data.ts"]